package com.hjusic.auth.domain.user.model;

public enum UserErrorCode {
  USER_NOT_FOUND,
  USER_CREATION_FAILED,
  USER_DELETION_FAILED,
  RESET_PASSWORD_TOKEN_VALIDATION_FAILED,
  UNAUTHENTICATED,
  VALIDATION_FAILED
}
